trigger:
- main

jobs:
- job: deploy_vm
  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - checkout: self

  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '2.1.x'

  - task: AzureCLI@2
    inputs:
      azureSubscription: 'vm_creation_test'
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        az group create --name VirtualMachines --location eastus
        az deployment group create --resource-group VirtualMachines --template-uri https://raw.githubusercontent.com/Azure/azure-quickstart-templates/master/101-vm-simple-linux/azuredeploy.json --parameters https://raw.githubusercontent.com/Azure/azure-quickstart-templates/master/101-vm-simple-linux/azuredeploy.parameters.json --parameters adminUsername=akhilvn@avnstudies.onmicrosoft.com servicePrincipalClientId=9d1f68a9-bc36-4e73-82b5-f2bee8ec1176 servicePrincipalSecret=-u.8Q~LwuEqQXvhSJs7EO7tfE7Ohn4fJPHkG.bZV vmName=test

  - task: AzureCLI@2
    inputs:
      azureSubscription: 'vm_creation_test'
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        VM_IP=$(az vm show -d --resource-group VirtualMachines --name test --query publicIps --output tsv)
        echo "VM IP Address: $VM_IP"
        echo "VM Outputs: $VM_IP" >> $(System.DefaultWorkingDirectory)/envFile

  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: '$(System.DefaultWorkingDirectory)/envFile'
      artifact: 'vmOutputs'
